org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
GENERATED_APP_APPLICATION_ID=kr.ac.kangwon.hai.generated.baseproject
GENERATED_APP_TASK_ID=task-unknown
GENERATED_APP_VERSION_CODE=2100000000
GENERATED_APP_VERSION_NAME=1.0.0
