name: kangwonmealalert

description: 강원대 학식 알리미
publish_to: 'none'

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
