name: kr_ac_kangwon_hai_geeknews_alert
description: "긱뉴스 알리미 Flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  workmanager: ^0.9.0+3
  url_launcher: ^6.3.1
  html: ^0.15.4
  xml: ^6.5.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
