name: geeknews_notifier
description: 뉴스하다 긱뉴스 최신글 알림 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  workmanager: ^0.7.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
